### ISSUE TITLE
광고 영역 찾는 로직을 개선할 것

### ISSUE THREAD

**Issue by kyungw00k** [kyungw00k/ads-finder#2]
AdBlock이 하는 방식과 동일한 혹은 그에 근접한 방법으로 수정할 필요가 있다.

**장점**
* 꾸준히 업데이트 되는 [광고 및 트래커 목록](https://easylist-downloads.adblockplus.org/easylist.txt) 사용 가능
* IFRAME이 아닌 SRC/HREF의 URL Pattern으로 좀 더 많은 광고 영역 및 트레커를 찾을 수 있음

**단점**
* 신규 로직 개발에 따르는 비용(또는 AdBlock에서 실제로 Ad를 Block 하는 로직 학습 필요)

**Comment by kyungw00k** [comment]
AdBlock은 내부적으로 다음과 같은 순서로 광고가 있는 Node들을 제거 또는 숨김 처리 한다.

1. Rule Set을 내려받은 후, 내부에서 사용하는 Filter(정규 표현식)로 변환한다.
2. Domain Filter 적용
    1. 페이지를 방문할 때 발생하는 모든 Resource(`img src`, `script src` 등등) URL의 도메인을 살펴보고
    2. Filter에 Match되면 제거하거나 숨긴다.
3. CSS Filter 적용
  1. 페이지 `onload` 이후에 모든 CSS RuleSet에 대해 query 한 후,
  2. 해당 Node를 (CSS로) 숨김 처리한다.
4. Success Callback 실행

**Comment by kyungw00k** [comment]
**TODO** 

* [ ] RuleSet Fetch & Parsing
  * RuleSet은 주기적으로 업데이트 해서 LocalStorage에 저장하면 되겠고..

* [ ] `Domain Filter 적용`을 위해 어떤 DOM이 Resource를 요청하는지 가로채는 방법 해결하기
  * `PhantomJS` 에서는 HTTP Request를 요청한 Node 정보를 알 수가 없다.
  * Safari 계열에서는 `beforeload` 이벤트를 사용할 수 있다.
  * Chrome 계열에서는 `chrome.webRequest.onBeforeRequest` API가 구현되어 있으면 사용이 가능한데, Electron에서는 ~~가능할 것 같다~~ [가능하다](http://github-bj.daocloud.io/atom/electron/blob/d9d821cea5a2425a4dde23f7eb630250cd237a60/spec/api-web-request-spec.js).

* [ ] `CSS Filter 적용`
  * RuleSet만 Parsing되어 있다면 onLoad 이후 찾을 수 있다.

**Comment by kyungw00k** [comment]
일단, 영역까지 찾아주는건 포기하자.
